get http://localhost:3000/api/persons


###

get http://localhost:3000/info


###
delete http://localhost:3000/api/persons/4

###
POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "Mary Ford",
    "number":"0700"
}